### ISSUE TITLE
Date Pattern

### ISSUE THREAD

**Issue by burredis** [flavioltonon/go-brazil#4]
Utilizei a lib para fazer algumas validação de CPF e como precisamos de algumas validações de data também, vêem a necessidade de ter essa funcionalidade aqui? Formatação para o padrão brasileiro dd/mm/YYYY, e casos em que recebe um data dd/MMM/YYYY e ainda sim retorna em dd/mm/YYYY

**Comment by flavioltonon** [comment]
Acredito que caberia como funcionalidade para a lib, sim. Pode ficar à vontade para abrir um PR com a mudança!
